/**:
  ros__parameters:
    base_frame_id: base_link
    map_frame_id: map

    publish_frequency: 10.0 # hz

    # smoother_type: Kalman Filter
    smoother_type: Factor Graph

    # Points Pre Processing
    scan_voxel_size: 0.5
    crop_min_x: -1.0
    crop_max_x: 1.0
    crop_min_y: -1.0
    crop_max_y: 1.0
    crop_min_z: -1.0
    crop_max_z: 1.0
    min_distance: 0.001

    # Scan Registration
    max_correspondence_distance: 2.0
    correspondence_randomness: 20
    max_iteration: 64
    omp_num_thread: 4
    transformation_epsilon: 0.01
    resolution: 1.0

    # ESKF
    acc_noise: 0.1
    gyro_noise: 0.1
    acc_bias_noise: 1e-5
    gyro_bias_noise: 1e-2
    translation_noise: 1e-6
    rotation_noise: 1e-6
    gravity: 9.80665

    # Local Map
    translation_threshold: 5.0
    rotation_threshold: 45.0
    voxel_map_resolution: 0.5
    map_removal_distance: 100.0
    max_submap_size: 20

    # IMU
    imu_calibration_time: 1.0
